function toast(msg){const t=document.getElementById("toast");t.innerText=msg;t.style.display="block";setTimeout(()=>{t.style.display="none"},2200)}
async function checkHealth(){try{const res=await fetch("/health");const data=await res.json();document.getElementById("healthBadge").innerHTML="云端检测："+data.status;toast("云端服务正常")}catch(e){document.getElementById("healthBadge").innerHTML="云端检测：异常";toast("云端检测失败")}}
function getCarIp(){return document.getElementById("carIp").value.trim().replace("http://","").replace("https://","").replace("/","")}
function connectVideo(){const ip=getCarIp();if(!ip){toast("请先输入小车 IP");return}const mode=document.getElementById("streamMode").value;const url=mode==="81"?`http://${ip}:81/stream`:`http://${ip}/stream`;const img=document.getElementById("videoImg");img.src=url+"?t="+Date.now();img.style.display="block";document.getElementById("videoPlaceholder").style.display="none";toast("正在连接视频："+url)}
async function sendCar(path){const ip=getCarIp();if(!ip){toast("请先输入小车 IP");return}try{await fetch(`http://${ip}/${path}`,{mode:"no-cors"});toast("指令已发送："+path)}catch(e){toast("指令发送失败，请检查小车 IP 和 WiFi")}}
function riskClass(risk){if(risk==="高风险")return"risk risk-high";if(risk==="中风险")return"risk risk-mid";return"risk risk-low"}
async function detectBlob(blob,filename){const fd=new FormData();fd.append("file",blob,filename);document.getElementById("resultPanel").innerHTML="<b>云端分析中：</b><br>图片上传中，请稍等...";toast("正在上传识别");const res=await fetch("/api/detect",{method:"POST",body:fd});const data=await res.json();if(!res.ok){document.getElementById("resultPanel").innerHTML="<b>识别失败：</b><br>"+JSON.stringify(data);toast("识别失败");return}renderDetection(data);toast("识别完成")}
async function uploadDetect(){const input=document.getElementById("fileInput");if(!input.files||input.files.length===0){toast("请先选择一张伸缩缝图片");return}try{await detectBlob(input.files[0],input.files[0].name||"upload.jpg")}catch(e){document.getElementById("resultPanel").innerHTML="<b>上传失败：</b><br>请检查服务器是否运行。";toast("上传失败")}}
async function captureFromCar(){const ip=getCarIp();if(!ip){toast("请先输入小车 IP");return}try{toast("正在从小车获取高清照片");const response=await fetch(`http://${ip}/capture_hq?t=${Date.now()}`);if(!response.ok){throw new Error("capture_hq failed")}const blob=await response.blob();await detectBlob(blob,"esp32cam_capture.jpg")}catch(e){toast("拍照采集失败，请检查 ESP32-CAM /capture_hq 接口")}}
function renderDetection(data){const raw=document.getElementById("rawImg");raw.src=data.raw_url+"?t="+Date.now();raw.style.display="block";document.getElementById("rawEmpty").style.display="none";const ana=document.getElementById("analysisImg");ana.src=data.analysis_url+"?t="+Date.now();ana.style.display="block";document.getElementById("anaEmpty").style.display="none";document.getElementById("resultPanel").innerHTML=`<b>病害分析报告：</b><br>巡检编号：${data.id}<br>病害类型：${data.disease_type}<br>病害等级：${data.disease_level}<br>风险等级：<span class="${riskClass(data.risk_level)}">${data.risk_level}</span><br>疑似区域数量：${data.suspect_count}<br>面积占比：${data.area_ratio}%<br>识别置信度：${data.confidence}<br>修复决策：${data.decision}<br>是否建议修复：${data.repairable?"是":"否"}<br>处理建议：${data.suggestion}<br><a href="${data.report_url}" target="_blank">打开检测报告</a>`}
function clearResult(){document.getElementById("fileInput").value="";document.getElementById("rawImg").style.display="none";document.getElementById("analysisImg").style.display="none";document.getElementById("rawEmpty").style.display="inline";document.getElementById("anaEmpty").style.display="inline";document.getElementById("resultPanel").innerHTML="<b>病害分析报告：</b><br>暂无识别结果。"}
checkHealth()
